(() => {
  const story = (titleZh, titleEn, zh, en) => ({ titleZh, titleEn, zh, en });
  const lineage = (data) => ({
    parents: [],
    parentNames: [],
    consorts: [],
    consortNames: [],
    children: [],
    childNames: [],
    siblings: [],
    siblingNames: [],
    notes: [],
    ...data
  });

  const olympianSiblings = ["hestia", "demeter", "hera", "hades", "poseidon", "zeus"];
  const titanSiblings = ["oceanus", "coeus", "crius", "hyperion", "iapetus", "theia", "rhea", "themis", "mnemosyne", "phoebe", "tethys", "cronus"];
  const heliadSiblings = ["helios", "selene", "eos"];
  const windSiblings = ["boreas", "zephyrus", "notus", "eurus"];
  const fateSiblings = ["clotho", "lachesis", "atropos"];
  const styxSiblings = ["nike", "kratos", "bia", "zelus"];
  const nereidSiblings = ["amphitrite", "thetis", "galatea"];
  const museSiblings = ["calliope", "clio", "erato", "euterpe", "melpomene", "polyhymnia", "terpsichore", "thalia-muse", "urania"];

  window.mythStories = {
    zeus: story("推翻克洛诺斯", "The overthrow of Cronus", "克洛诺斯吞下自己的孩子，瑞亚把年幼的宙斯藏起。宙斯长大后逼父亲吐出兄弟姐妹，联合他们推翻泰坦，成为新的天界秩序之王。", "Cronus swallowed his children until Rhea hid the infant Zeus. When Zeus grew up, he forced Cronus to release his siblings and led the new gods against the Titans."),
    hera: story("神后的尊严", "The queen defends her rank", "赫拉最著名的故事往往围绕她捍卫婚姻与神后地位展开。她惩罚宙斯的情人与私生子，并不是单纯嫉妒，而是在维护奥林匹斯的合法秩序。", "Hera is famous for defending marriage and her rank as queen. Her punishments of Zeus's lovers and children show the cost of broken divine order."),
    poseidon: story("争夺雅典", "The contest for Athens", "波塞冬与雅典娜争夺雅典城，他用三叉戟击地献出海水或战马，雅典娜献出橄榄树。城邦选择了能带来和平、粮油与技艺的橄榄树。", "Poseidon competed with Athena for Athens, striking the ground with his trident. Athena offered the olive tree, and the city chose the gift of peace, oil, and craft."),
    demeter: story("寻找珀耳塞福涅", "The search for Persephone", "女儿被带入冥界后，德墨忒耳手持火炬四处寻找。她的悲伤使大地停止生长，直到母女每年重逢，世界才重新进入丰收。", "After Persephone was taken below, Demeter searched with torches and let the earth grow barren. The yearly reunion of mother and daughter explains the return of growth."),
    athena: story("从宙斯头中诞生", "Born from the head of Zeus", "宙斯吞下墨提斯后头痛欲裂，赫淮斯托斯劈开他的头，雅典娜全副武装跃出。这个故事让她一开始就带着智慧、战略和武备。", "After Zeus swallowed Metis, his head split with pain. Hephaestus opened it, and Athena sprang out fully armed, already a goddess of strategy and wisdom."),
    apollo: story("阿波罗与达芙妮", "Apollo and Daphne", "阿波罗追求宁芙达芙妮，她向父亲求救，变成月桂树。阿波罗把月桂作为自己的神圣植物，爱情的失败变成诗歌与荣耀的标志。", "Apollo pursued the nymph Daphne, who escaped by becoming a laurel tree. Apollo made the laurel sacred, turning failed desire into a symbol of poetry and honor."),
    artemis: story("阿克泰翁的冒犯", "Actaeon's trespass", "猎人阿克泰翁无意看见阿耳忒弥斯沐浴，女神把他变成鹿。他被自己的猎犬追咬而死，故事强调她对边界和贞洁的严厉守护。", "Actaeon saw Artemis bathing and was changed into a stag. His own hounds tore him apart, a stark myth about violating the goddess's sacred boundaries."),
    ares: story("被铜网困住", "Caught in the bronze net", "阿瑞斯与阿佛洛狄忒相恋，赫淮斯托斯铸出隐形铜网把两人困住，召众神观看。暴烈的战神在这个故事里也会被工匠的智慧羞辱。", "Ares and Aphrodite were trapped by Hephaestus in a subtle bronze net. The war god's force was publicly defeated by the smith god's craft."),
    aphrodite: story("金苹果与特洛伊", "The golden apple and Troy", "帕里斯在三位女神中判定阿佛洛狄忒最美，因为她许诺让他得到海伦。这个选择点燃了欲望、荣誉和战争，成为特洛伊战争的导火索。", "Paris judged Aphrodite the fairest after she promised him Helen. The choice joined desire, honor, and rivalry, helping set the Trojan War in motion."),
    hephaestus: story("工匠的铜网", "The smith's bronze net", "赫淮斯托斯发现阿佛洛狄忒与阿瑞斯私会，便打造看不见的铜网。故事让他不只是火神，也是用技术和耐心胜过强者的工匠。", "Hephaestus discovered Aphrodite and Ares together and forged an invisible net. The tale shows him as the craftsman whose patient skill can outwit brute force."),
    hermes: story("偷走阿波罗的牛", "The stolen cattle of Apollo", "赫尔墨斯出生当天就溜出山洞，偷走阿波罗的牛，还发明里拉琴。最终他用音乐化解冲突，从小就显出信使、盗贼和谈判者的本领。", "On the day he was born, Hermes stole Apollo's cattle and invented the lyre. Music turned the quarrel into exchange, revealing his wit and talent for negotiation."),
    dionysus: story("海盗变海豚", "Pirates turned into dolphins", "海盗把年轻的狄俄尼索斯绑上船，以为能卖个好价钱。藤蔓爬满船身，幻象和恐惧降临，海盗跳海变成海豚。", "Pirates kidnapped Dionysus, thinking him a valuable youth. Vines covered the ship, divine terror appeared, and the pirates leapt into the sea as dolphins."),
    hades: story("带走珀耳塞福涅", "The taking of Persephone", "哈迪斯从裂开的土地中驾车出现，把珀耳塞福涅带入冥界。这个故事并不把他写成恶魔，而是把婚姻、死亡和季节秩序绑在一起。", "Hades rose from the opened earth and took Persephone below. The myth ties marriage, death, and seasonal order together rather than making him a simple villain."),
    hestia: story("选择炉火", "Choosing the hearth", "赫斯提亚拒绝波塞冬和阿波罗的求婚，向宙斯请求永守处女之身。她得到每个家庭与城邦中心的炉火，成为最安静也最稳定的神。", "Hestia refused the suits of Poseidon and Apollo and asked Zeus to remain a virgin. She received the hearth, the quiet center of every home and city."),
    persephone: story("石榴籽", "The pomegranate seeds", "珀耳塞福涅在冥界吃下石榴籽，因此不能完全回到母亲身边。她一年在冥界、一年回到大地，成为春天与冥后的双重女神。", "Persephone ate pomegranate seeds in the underworld and could not return entirely. Her divided year makes her both spring maiden and queen below."),
    eros: story("厄洛斯与普绪刻", "Eros and Psyche", "普绪刻因美貌遭阿佛洛狄忒嫉恨，却与厄洛斯相爱。她经历考验后获得不朽，故事把爱情写成迷恋、信任与灵魂成长。", "Psyche's beauty angered Aphrodite, yet Eros loved her. After severe trials she gained immortality, making the tale a myth of love, trust, and the soul's growth."),
    nike: story("站到宙斯一边", "Standing with Zeus", "泰坦战争中，尼刻和兄弟姐妹最早随母亲斯堤克斯投向宙斯。胜利女神从此常在宙斯身边，象征新秩序获得合法荣耀。", "In the Titan war, Nike and her siblings came early to Zeus with their mother Styx. Victory then stood beside the new order of Olympus."),
    hebe: story("赫拉克勒斯的不朽婚礼", "The immortal marriage of Heracles", "赫柏原为诸神斟神酒，后来嫁给升入奥林匹斯的赫拉克勒斯。她象征英雄完成苦难后获得青春与不朽。", "Hebe served nectar to the gods and later married Heracles after his apotheosis. She marks the hero's passage from suffering into immortal youth."),
    iris: story("冥河之水", "Water from the Styx", "伊里斯常被派去取冥河之水，让诸神以最严厉的方式起誓。彩虹信使的速度在这里服务于神圣誓言。", "Iris was sent to fetch water from the Styx so the gods could swear their most binding oaths. The rainbow messenger serves divine truth and speed."),
    helios: story("法厄同驾太阳车", "Phaethon and the sun chariot", "赫利俄斯的儿子法厄同请求驾太阳车，却控制不住烈马，烧焦大地。宙斯击落他，显示太阳秩序不是凡人能轻易掌握的力量。", "Helios's son Phaethon tried to drive the sun chariot but lost control and scorched the earth. Zeus struck him down, proving solar order is not a child's toy."),
    selene: story("沉睡的恩底弥翁", "The sleeping Endymion", "塞勒涅爱上永远沉睡的恩底弥翁，每夜以月光探望他。这个故事让月亮带上静谧、梦境和无法完成的爱情。", "Selene loved Endymion, who slept eternally, and visited him by moonlight. The myth gives the moon a mood of dream, stillness, and unreachable love."),
    eos: story("提托诺斯的愿望", "The wish for Tithonus", "厄俄斯为爱人提托诺斯求得永生，却忘了求永葆青春。提托诺斯日渐衰老，故事提醒人们永恒若没有限度也会变成痛苦。", "Eos asked immortality for Tithonus but forgot eternal youth. He kept aging forever, a myth about the danger of wishing without wisdom."),
    hecate: story("火炬中的见证", "The torch-bearing witness", "珀耳塞福涅失踪时，赫卡忒听见她的呼喊，手持火炬帮助德墨忒耳寻找。她因此成为岔路、夜行和隐秘知识的引路者。", "When Persephone vanished, Hecate heard her cry and joined Demeter with torches. She became a guide through night, crossroads, and hidden knowledge."),
    pan: story("绪任克斯与排箫", "Syrinx and the panpipes", "潘追逐宁芙绪任克斯，她化为芦苇逃脱。潘把芦苇制成排箫，于是野性的追逐被转化成山林音乐。", "Pan pursued the nymph Syrinx, who escaped by becoming reeds. He cut the reeds into pipes, turning wild pursuit into rustic music."),
    asclepius: story("医术触及死亡", "Healing that reached death", "阿斯克勒庇俄斯医术高到能使死人复生，破坏了生死边界。宙斯用雷霆击杀他，后来他又成为医学崇拜的神圣核心。", "Asclepius became so skilled that he could revive the dead, threatening the boundary of mortality. Zeus struck him down, yet his cult became central to healing."),
    hygieia: story("医神家族的健康之碗", "The healing bowl", "希吉亚常伴随阿斯克勒庇俄斯，以蛇与药碗象征健康。她的故事不在惊险奇迹，而在提醒人们预防与日常秩序也是神圣医术。", "Hygieia appears beside Asclepius with a serpent and bowl. Her mythic role is quieter than miracle healing: prevention and daily health are also sacred."),
    hypnos: story("让宙斯沉睡", "Putting Zeus to sleep", "赫拉曾请求许普诺斯让宙斯入睡，以便干预特洛伊战局。睡神连宙斯也能影响，但他必须谨慎，因为天王醒来后的怒火极可怕。", "Hera persuaded Hypnos to lull Zeus asleep during the Trojan War. Even the king of gods could be touched by sleep, though the risk was terrifying."),
    thanatos: story("西西弗斯锁住死亡", "Sisyphus chains Death", "狡猾的西西弗斯一度把塔那托斯锁住，世上无人再死。阿瑞斯释放死亡后，秩序恢复，故事说明死亡虽可怕却不可缺少。", "Sisyphus once chained Thanatos, and no one could die. When Ares released Death, order returned, showing that mortality is frightening but necessary."),
    morpheus: story("梦中传信", "A message in a dream", "在俄维德的故事里，墨菲斯能在梦中化成人形，把真实消息带给沉睡者。他让梦不只是幻觉，也成为神意进入心灵的门。", "In Ovid's tale, Morpheus takes human shape in dreams to deliver truth. He turns dreaming into a doorway through which divine messages enter the mind."),
    nemesis: story("纳耳喀索斯的回声", "The judgment of Narcissus", "纳耳喀索斯轻视爱他的人，涅墨西斯让他爱上水中的自己。他无法拥抱倒影，最终被自己的傲慢吞没。", "Narcissus scorned those who loved him, so Nemesis made him fall for his own reflection. His pride turned desire into punishment."),
    tyche: story("命运的舵", "The rudder of fortune", "堤喀常手持舵与丰饶角，象征城市命运会突然转向。她的代表故事不是单一冒险，而是城邦兴衰都可能被偶然之手改变。", "Tyche carries a rudder and cornucopia because a city's fortune can suddenly turn. Her mythic force is the unstable fate of public life."),
    themis: story("关于忒提斯之子的预言", "The prophecy about Thetis", "忒弥斯提醒众神，忒提斯之子将强过父亲。这个神法般的预言让宙斯放弃追求忒提斯，也间接引向阿喀琉斯的诞生。", "Themis warned that Thetis would bear a son greater than his father. The prophecy made Zeus avoid her and helped lead to the birth of Achilles."),
    leto: story("提洛岛分娩", "The birth on Delos", "被赫拉追迫的勒托无处安身，最终在漂浮的提洛岛生下阿波罗与阿耳忒弥斯。她的故事是神圣母亲寻找避难所的故事。", "Pursued by Hera, Leto found refuge on Delos and gave birth to Apollo and Artemis. Her myth is a story of divine motherhood and exile."),
    rhea: story("裹布中的石头", "The stone in swaddling cloth", "瑞亚不愿再让孩子被克洛诺斯吞下，便把石头包成婴儿交给丈夫。这个小小骗局保住宙斯，也改写了神族历史。", "Rhea wrapped a stone as a baby and gave it to Cronus instead of Zeus. The small deception saved the child who would overturn the Titans."),
    cronus: story("吞下自己的孩子", "Swallowing his children", "克洛诺斯害怕预言成真，逐一吞下与瑞亚所生的孩子。越想阻止命运，他越把反抗的理由送到宙斯手中。", "Cronus swallowed his children to prevent a prophecy that one would overthrow him. His fear of fate created the very rebellion he dreaded."),
    oceanus: story("环绕世界的大河", "The river around the world", "俄刻阿诺斯不像克洛诺斯那样直接争权，他更像环绕世界的边界水流。许多河流、泉水和水泽女神都从他的家族展开。", "Oceanus is less a throne-seeker than the great river encircling the world. From his line come rivers, springs, and many water nymphs."),
    tethys: story("河流之母", "Mother of rivers", "忒堤斯与俄刻阿诺斯生下众多河神与俄刻阿尼得斯。她的故事像一张水系地图，把世界的滋养力量连成家族。", "Tethys and Oceanus produced the rivers and Oceanids. Her story is almost a water map, turning the world's nourishment into genealogy."),
    hyperion: story("光明家族", "The family of light", "许珀里翁与忒亚生下太阳、月亮和黎明。这个家族让白昼的三个阶段变成可以理解的神圣亲属。", "Hyperion and Theia fathered Helios, Selene, and Eos. Their family makes the sun, moon, and dawn into a clear divine line of light."),
    theia: story("光辉之母", "Mother of radiance", "忒亚是赫利俄斯、塞勒涅和厄俄斯的母亲，也与宝石和贵金属的光泽相连。她把可见世界的闪耀变成神性。", "Theia is mother of Helios, Selene, and Eos, and is linked with the shine of precious things. She gives visible radiance a divine ancestry."),
    coeus: story("通向德尔斐的血脉", "The line toward Delphi", "科俄斯本人故事不多，但他与福柏生下勒托。通过勒托，他成为阿波罗和阿耳忒弥斯的外祖父，连接泰坦与德尔斐预言。", "Coeus has few independent myths, but with Phoebe he fathers Leto. Through her, he becomes ancestor of Apollo and Artemis and links Titans to prophecy."),
    phoebe: story("神谕的祖母", "Grandmother of prophecy", "福柏的名字带有明亮意味，她与神谕传统相连。她的女儿勒托生下阿波罗，使预言之光进入奥林匹斯神系。", "Phoebe's name suggests brightness and she is tied to oracular tradition. Through Leto and Apollo, prophetic light enters the Olympian line."),
    iapetus: story("反叛者的父亲", "Father of the challengers", "伊阿珀托斯最有名不是自己的战斗，而是他的儿子们：普罗米修斯盗火，阿特拉斯撑天，厄庇墨透斯接受潘多拉。", "Iapetus is remembered through his sons: Prometheus steals fire, Atlas bears the sky, and Epimetheus accepts Pandora."),
    crius: story("星与风的祖父", "Grandfather of stars and winds", "克利俄斯是较沉默的泰坦，但他的后代连接星辰、风与竞争。通过阿斯特赖俄斯，他的血脉吹向天空。", "Crius is a quiet Titan, yet his descendants link stars, winds, and rivalry. Through Astraeus his line moves into the sky."),
    mnemosyne: story("九夜与九缪斯", "Nine nights and nine Muses", "宙斯与记忆女神谟涅摩绪涅相会九夜，生下九位缪斯。希腊人由此把诗歌、历史、音乐与记忆本身连在一起。", "Zeus lay with Mnemosyne for nine nights, and the nine Muses were born. Poetry, history, and music are thus children of memory."),
    prometheus: story("盗火给人类", "Stealing fire for humankind", "普罗米修斯从神那里盗取火种给人类，宙斯把他锁在高加索山，让鹰啄食他的肝。文明的礼物因此带着反抗的代价。", "Prometheus stole fire for humanity, and Zeus chained him to a mountain where an eagle tore his liver. Civilization arrives with the cost of rebellion."),
    epimetheus: story("接受潘多拉", "Accepting Pandora", "普罗米修斯警告弟弟不要收宙斯的礼物，但厄庇墨透斯接受了潘多拉。灾厄从盒中散出，只剩希望留在人间。", "Prometheus warned his brother not to accept Zeus's gift, but Epimetheus received Pandora. Troubles escaped from the jar, leaving hope behind."),
    atlas: story("肩上的天空", "The sky on his shoulders", "泰坦战败后，阿特拉斯被罚在西方尽头支撑天空。后来赫拉克勒斯短暂替他承重，显示这份惩罚沉重到连英雄也难久持。", "After the Titans fell, Atlas was punished to hold up the sky. Heracles briefly took the burden, showing how heavy that cosmic sentence was."),
    metis: story("被吞下的智慧", "Wisdom swallowed", "墨提斯怀着雅典娜时，宙斯因预言吞下她。智慧没有消失，而是在宙斯体内变成雅典娜的诞生。", "When Metis was pregnant with Athena, Zeus swallowed her because of prophecy. Wisdom did not vanish; it emerged from within Zeus as Athena."),
    dione: story("受伤的阿佛洛狄忒", "Aphrodite comforted", "在《伊利亚特》中，阿佛洛狄忒受伤后回到母亲狄俄涅身边。狄俄涅安慰她，呈现出爱神背后温柔的母系版本。", "In the Iliad, wounded Aphrodite returns to her mother Dione. Dione comforts her, preserving a gentler maternal version of Aphrodite's genealogy."),
    astraeus: story("风与星辰之父", "Father of winds and stars", "阿斯特赖俄斯与黎明女神厄俄斯结合，生下诸风与星辰。于是清晨、风向和夜空在一个家族中连成循环。", "Astraeus and Eos fathered the winds and stars. Dawn, weather, and the night sky become one connected family cycle."),
    amphitrite: story("海后被海豚劝回", "The dolphin's persuasion", "安菲特里忒起初逃避波塞冬的追求，海豚劝她回到海神身边。她成为海后，海豚也因此获得星座荣耀。", "Amphitrite first fled Poseidon, but a dolphin persuaded her to return. She became queen of the sea, and the dolphin won celestial honor."),
    triton: story("海螺号角", "The conch trumpet", "特里同吹响海螺，能让海浪平息或翻涌。他把波塞冬的海权变成可听见的号令。", "Triton blows a conch that can calm or stir the waves. He turns Poseidon's sea power into an audible command."),
    proteus: story("被墨涅拉俄斯抓住", "Menelaus captures Proteus", "墨涅拉俄斯为了回家，抓住会变形的普罗透斯。海神不断变成野兽、火与水，最终说出归航的秘密。", "Menelaus seized Proteus to learn how to return home. The sea god changed into beasts, fire, and water before revealing the needed truth."),
    nereus: story("诚实的海老人", "The truthful old man of the sea", "涅柔斯被称为海老人，智慧而不说谎。赫拉克勒斯曾抓住他寻求道路，老海神的知识来自深海的古老记忆。", "Nereus, the Old Man of the Sea, is wise and truthful. Heracles once wrestled him for guidance, drawing knowledge from the ancient sea."),
    thetis: story("为阿喀琉斯求铠甲", "Armor for Achilles", "忒提斯听见阿喀琉斯的悲痛，去找赫淮斯托斯为儿子打造新铠甲。母亲的爱在《伊利亚特》中化成英雄最后的光辉。", "Thetis heard Achilles grieving and asked Hephaestus to forge new armor for him. A mother's love becomes the hero's final radiance in the Iliad."),
    galatea: story("阿喀斯与波吕斐摩斯", "Acis and Polyphemus", "海中宁芙伽拉忒亚爱着青年阿喀斯，独眼巨人波吕斐摩斯因嫉妒杀死他。伽拉忒亚把阿喀斯化为清泉，让爱情以水继续流动。", "The sea nymph Galatea loved Acis, but jealous Polyphemus killed him. She changed Acis into a spring, letting love continue as water."),
    boreas: story("掳走俄瑞梯亚", "The abduction of Oreithyia", "北风玻瑞阿斯爱上雅典公主俄瑞梯亚，最终以风暴之力把她带走。这个故事解释了北风与雅典王族的神话联系。", "Boreas loved the Athenian princess Oreithyia and carried her away by storm. The myth connects the north wind to Athenian royal ancestry."),
    zephyrus: story("西风与风信子", "The west wind and Hyacinthus", "在一种版本里，西风泽费罗斯嫉妒阿波罗与许阿金托斯，吹偏铁饼导致少年死亡。柔和的西风也有危险的情绪。", "In one version, Zephyrus grew jealous of Apollo and Hyacinthus and blew a discus off course. Even the gentle west wind can turn destructive."),
    notus: story("潮湿的南风", "The wet south wind", "诺托斯没有单一最著名的冒险，却常带来夏末暴雨与作物风险。古人把他想成让天空沉重、海面危险的风。", "Notus has no single dominant adventure, but he brings late-summer storms and risk to crops. Ancient poets imagined him as a heavy, dangerous south wind."),
    eurus: story("暴躁的东风", "The restless east wind", "欧罗斯常被视作不稳定的东风，给航海带来麻烦。作为风神谱系的一员，他提醒读者方向本身也能成为神力。", "Eurus is the unstable east wind that troubles sailors. As one of the wind gods, he makes direction itself feel like a divine force."),
    aeolus: story("奥德修斯的风袋", "Odysseus and the bag of winds", "埃俄罗斯把诸风装进袋中交给奥德修斯，只留下顺风送他回乡。船员误以为袋中有财宝，打开后风暴把他们吹回远方。", "Aeolus gave Odysseus a bag holding the winds, leaving only a fair breeze. The crew opened it, thinking it held treasure, and the storm blew them away."),
    glaucus: story("吃下神草", "The magic herb", "渔夫格劳科斯看见鱼吃草后复活，便自己也尝了神草。他跳入海中变成海神，人的生活从此被海水改写。", "Glaucus saw fish revive after touching a magic herb and ate it himself. He leapt into the sea and became a sea god."),
    leucothea: story("救助奥德修斯", "Saving Odysseus", "成为海神的琉科忒亚在风暴中看见奥德修斯，给他一条神圣面纱保命。她的故事把悲剧母亲转化为海上救援者。", "Leucothea saw Odysseus in a storm and gave him a divine veil to survive. Her myth turns a tragic mortal mother into a sea rescuer."),
    gaia: story("让克洛诺斯出手", "Gaia arms Cronus", "乌拉诺斯把孩子压在盖亚体内，盖亚痛苦不堪，铸出镰刀交给克洛诺斯。大地母亲发动了第一次神族更替。", "Uranus trapped his children within Gaia, and she forged a sickle for Cronus. The earth mother set the first divine succession in motion."),
    uranus: story("被克洛诺斯推翻", "Overthrown by Cronus", "乌拉诺斯压制自己的孩子，最终被儿子克洛诺斯用镰刀推翻。天空与大地被分开，神族历史从家庭暴力进入王权更替。", "Uranus oppressed his children until Cronus overthrew him with a sickle. Sky and earth were separated, and divine history became succession conflict."),
    nyx: story("连宙斯也敬畏", "Feared even by Zeus", "《伊利亚特》中，许普诺斯逃到母亲尼克斯身边，宙斯因敬畏夜女神而停止追赶。尼克斯的古老力量高过许多奥林匹斯冲突。", "In the Iliad, Hypnos escaped to his mother Nyx, and Zeus stopped because he respected Night. Her ancient power stands beyond many Olympian quarrels."),
    erebus: story("幽暗生出光", "Darkness gives birth to light", "厄瑞玻斯与尼克斯结合，生下埃忒耳与赫墨拉。幽暗和夜晚反而成为明亮空气与白昼的父母。", "Erebus and Nyx produce Aether and Hemera. Darkness and night paradoxically become parents of bright air and day."),
    tartarus: story("泰坦的牢狱", "The prison of the Titans", "宙斯战胜泰坦后，把许多敌人囚在塔耳塔洛斯。它既是深渊也是神格，是宇宙最底层的惩罚空间。", "After Zeus defeated the Titans, many enemies were shut in Tartarus. It is both a god and the deepest prison-space of the cosmos."),
    aether: story("神明呼吸的上层空气", "The upper air of the gods", "埃忒耳代表凡人空气之上的明亮气层。作为夜与幽暗的孩子，他让光明从黑暗谱系中升起。", "Aether is the bright upper air above mortal breath. As child of Night and Darkness, he shows light rising from a dark genealogy."),
    hemera: story("昼夜交替", "The exchange of day and night", "赫墨拉与尼克斯像轮班一样经过同一门槛，一个进入世界，另一个退回居所。白昼因此被写成家庭秩序中的每日交替。", "Hemera and Nyx pass the same threshold in alternation: one enters the world as the other withdraws. Day becomes a daily family rhythm."),
    pontus: story("大海本身的父亲", "Father of the ancient sea", "蓬托斯不是波塞冬式的海王，而是海本身的原初形态。他与盖亚生出涅柔斯等古老海神。", "Pontus is not a sea-king like Poseidon but the primordial Sea itself. With Gaia he fathers ancient sea powers such as Nereus."),
    chaos: story("最初的裂隙", "The first chasm", "卡俄斯在神谱开端出现，更像一个张开的空隙而非现代意义的混乱。万物从这个裂隙之后逐步获得形状和关系。", "Chaos begins the Theogony as a yawning gap rather than modern disorder. After this chasm, beings gradually gain form and relation."),
    phanes: story("宇宙蛋中的显现", "The cosmic egg", "在奥尔弗斯传统里，法涅斯从宇宙蛋中显现，带着光、翅膀和创生力量。他属于另一条神谱，用来解释万物如何第一次显形。", "In Orphic tradition, Phanes emerges from the cosmic egg with light, wings, and generative power. He belongs to a different creation genealogy."),
    clotho: story("纺出生命线", "Spinning the thread", "克洛托负责把生命之线纺出。她的动作很小，却代表一个生命被纳入命运织物的开始。", "Clotho spins the thread of life. The gesture is small, but it marks the beginning of a life within the fabric of fate."),
    lachesis: story("丈量命运", "Measuring destiny", "拉刻西斯丈量生命之线，决定一个人能获得多长时间、多少份额。她让命运看起来像可被量尺分配的东西。", "Lachesis measures the thread of life, assigning length and portion. She makes destiny feel like something allotted by measure."),
    atropos: story("剪断生命线", "Cutting the thread", "阿特罗波斯负责剪断生命线，名字有不可转回之意。她的剪刀象征每个故事终会抵达不能重写的一刻。", "Atropos cuts the thread of life, and her name suggests the irreversible. Her shears mark the moment a story can no longer be rewritten."),
    eris: story("不和的金苹果", "The apple of discord", "厄里斯未被邀请参加婚宴，便丢下一只写给最美女神的金苹果。三女神争夺它，帕里斯审判随之引向特洛伊战争。", "Excluded from a wedding, Eris threw down a golden apple for the fairest goddess. The rivalry led to the Judgment of Paris and toward Troy."),
    harmonia: story("被诅咒的项链", "The cursed necklace", "哈耳摩尼亚与卡德摩斯的婚礼盛大，众神送上礼物；其中项链却带来后代灾难。和谐女神的婚礼反而藏着悲剧种子。", "Harmonia's wedding to Cadmus was splendid, but one divine necklace brought disaster to her descendants. A goddess of harmony carries a seed of tragedy."),
    enyo: story("战场上的毁灭", "Destruction on the battlefield", "厄倪俄常伴随阿瑞斯，出现在城市被毁、火焰四起的场景中。她不是战略，而是战争失控后留下的尖叫。", "Enyo accompanies Ares in scenes of burning cities and battle terror. She is not strategy but the scream left when war breaks loose."),
    deimos: story("阿瑞斯战车旁的恐惧", "Fear beside Ares", "得摩斯与福波斯常随阿瑞斯进入战场。一个代表恐惧，一个代表惊慌，让战争在身体开战前先压垮人的心。", "Deimos and Phobos attend Ares in battle. Fear and panic break the mind before weapons break the body."),
    phobos: story("让敌军溃散", "Panic in battle", "福波斯的名字后来进入 phobia 一词。他在战场上不是单纯吓人，而是让队形和理智突然崩塌的力量。", "Phobos gives his name to phobia. On the battlefield he is the force that makes formations and reason collapse."),
    eileithyia: story("勒托的产痛", "Leto's labor", "赫拉拖延厄勒梯亚前往提洛岛，使勒托分娩艰难。分娩女神的到来与迟到，都能决定神圣出生的命运。", "Hera delayed Eileithyia from reaching Delos, making Leto's labor difficult. The birth goddess's arrival, or delay, decides the fate of delivery."),
    peitho: story("阿佛洛狄忒身边的说服", "Persuasion beside Aphrodite", "佩托常伴随阿佛洛狄忒，说明爱情不只靠美貌，也靠语言、姿态和心理的引导。她把欲望变成愿意靠近的理由。", "Peitho stands beside Aphrodite, showing that love uses speech, gesture, and persuasion as well as beauty."),
    hymen: story("婚歌中的呼唤", "The wedding call", "古希腊婚礼会呼唤许门之名，希望婚歌带来顺利结合。这个小神像一声祝福，把私人爱情交给公共仪式。", "Greek weddings invoked Hymen in song, asking for a blessed union. He turns private love into a public ritual of joining."),
    priapus: story("花园边界的守护者", "Guardian of the garden boundary", "普里阿普斯被放在花园和边界处，既祈求丰产也威吓闯入者。他的粗野形象属于土地肥力和边界保护。", "Priapus guarded gardens and boundaries, promising fertility and threatening intruders. His crude image belongs to abundance and protection."),
    anteros: story("回应之爱", "Love returned", "安忒洛斯被赠予厄洛斯作伙伴后，厄洛斯才真正成长。故事说明爱如果得不到回应，就会停滞；互相承认才让爱成熟。", "Anteros was given as a companion to Eros, who then grew. The myth says love needs response and recognition to mature."),
    kratos: story("锁住普罗米修斯", "Binding Prometheus", "在《被缚的普罗米修斯》中，克拉托斯执行宙斯命令，把盗火者钉在山岩上。他代表王权落地时冷硬的力量。", "In Prometheus Bound, Kratos enforces Zeus's order and helps fasten the fire-thief to the rock. He is power as execution."),
    bia: story("沉默的暴力", "Silent force", "比亚与克拉托斯一起押送普罗米修斯。她几乎不说话，却正因沉默而可怕，象征不解释、不商量的强制。", "Bia escorts Prometheus with Kratos. She says little, and that silence makes her frightening: force that does not negotiate."),
    zelus: story("竞争站上奥林匹斯", "Rivalry joins Olympus", "泽洛斯与尼刻、克拉托斯、比亚一起最早支持宙斯。竞争与热忱也被纳入新秩序，成为推动胜利的心理能量。", "Zelus joined Zeus early with Nike, Kratos, and Bia. Rivalry and zeal become part of the energy that drives victory."),
    aglaea: story("光辉的美惠", "The shining Grace", "阿格莱亚是三美惠之一，后来常被写作赫淮斯托斯的妻子。她让工匠之火旁出现优雅、欢愉和社交光辉。", "Aglaea is one of the Charites and is often named as Hephaestus's wife. She brings grace and social radiance beside the forge."),
    calliope: story("俄耳甫斯的歌声", "The voice of Orpheus", "卡利俄佩常被说成俄耳甫斯的母亲。史诗缪斯的血脉让歌声拥有改变人、兽和冥界的力量。", "Calliope is often called the mother of Orpheus. Through the epic Muse, song gains power over people, animals, and even the underworld."),
    clio: story("让行动成为历史", "Making deeds into history", "克利俄掌管历史，她的代表故事是把英雄行动保存为可传述的名声。没有她，胜利很快会从记忆中消失。", "Clio governs history, preserving deeds as fame that can be told. Without her, even victory would fade from memory."),
    erato: story("爱情诗的召唤", "The call of love poetry", "厄拉托的名字与爱相连，诗人召唤她来写柔情、婚歌和抒情诗。她把私人心动变成有节奏的语言。", "Erato's name is tied to love, and poets call on her for lyric and wedding song. She turns private feeling into measured speech."),
    euterpe: story("令人愉悦的笛声", "The delight of the flute", "欧忒耳佩常持双管笛，代表音乐让心灵变明亮的力量。她的故事藏在每一次诗歌被唱出来的时刻。", "Euterpe carries the double flute and represents the delight music brings. Her myth lives whenever poetry becomes song."),
    melpomene: story("悲剧面具", "The tragic mask", "墨尔波墨涅手持悲剧面具，让痛苦被放上舞台。她不是制造悲伤，而是把灾难变成可被凝视和理解的形式。", "Melpomene holds the tragic mask, placing suffering on stage. She does not create grief; she gives disaster a form the audience can face."),
    polyhymnia: story("静默的圣歌", "The silent sacred hymn", "波吕许谟尼亚常被画成沉思、蒙面纱的缪斯。她提醒人们，最庄严的歌声往往从静默和敬畏中开始。", "Polyhymnia is often veiled and contemplative. She reminds us that sacred song often begins in silence and reverence."),
    terpsichore: story("舞步中的诗", "Poetry in dance", "忒耳普西科瑞掌管舞蹈与合唱。她的故事不是一场战争，而是让诗、乐、身体节奏在祭典中合为一种艺术。", "Terpsichore rules dance and choral song. Her myth joins poetry, music, and bodily rhythm into festival art."),
    "thalia-muse": story("喜剧面具", "The comic mask", "塔利亚手持喜剧面具和牧杖，守护笑声、机智与牧歌。她让舞台不仅能承受悲剧，也能以笑声恢复生活。", "Thalia holds the comic mask and pastoral staff. She lets the stage answer tragedy with wit, laughter, and the renewal of ordinary life."),
    urania: story("星图上的秩序", "Order on the star map", "乌拉尼亚持天球与圆规，象征古代天文学中的数学美感。她让仰望星空变成理解宇宙秩序的学问。", "Urania carries the celestial globe and compass. She turns looking at the stars into the disciplined art of understanding cosmic order."),
    maia: story("山洞中诞生赫尔墨斯", "Hermes born in the cave", "玛亚住在山洞中，与宙斯生下赫尔墨斯。婴儿赫尔墨斯当天就偷牛、发明里拉，母亲的隐居山洞孕育出最机灵的神。", "Maia lived in a cave and bore Hermes to Zeus. The infant god stole cattle and invented the lyre the same day, turning hidden birth into quicksilver wit.")
  };

  window.mythLineage = {
    zeus: lineage({ parents: ["cronus", "rhea"], consorts: ["hera", "demeter", "leto", "mnemosyne", "maia", "metis", "dione"], children: ["athena", "apollo", "artemis", "ares", "hebe", "eileithyia", "hermes", "dionysus", "persephone", "calliope", "clio", "erato", "euterpe", "melpomene", "polyhymnia", "terpsichore", "thalia-muse", "urania", "aglaea"], siblings: olympianSiblings.filter((id) => id !== "zeus"), notes: ["宙斯的配偶与子女在古代文本中非常多；此处只列站内人物和最有助于理解主线的关系。"] }),
    hera: lineage({ parents: ["cronus", "rhea"], consorts: ["zeus"], children: ["ares", "hebe", "eileithyia", "hephaestus"], siblings: olympianSiblings.filter((id) => id !== "hera"), notes: ["赫淮斯托斯有时被说成赫拉独自产下，有时列为宙斯与赫拉之子。"] }),
    poseidon: lineage({ parents: ["cronus", "rhea"], consorts: ["amphitrite"], children: ["triton"], siblings: olympianSiblings.filter((id) => id !== "poseidon") }),
    demeter: lineage({ parents: ["cronus", "rhea"], consorts: ["zeus"], children: ["persephone"], siblings: olympianSiblings.filter((id) => id !== "demeter") }),
    athena: lineage({ parents: ["zeus", "metis"], siblings: ["apollo", "artemis", "ares", "hermes", "dionysus", "persephone"], notes: ["主流故事中，雅典娜在宙斯吞下墨提斯后从宙斯头中诞生。"] }),
    apollo: lineage({ parents: ["zeus", "leto"], children: ["asclepius"], childNames: ["Aristaeus", "Orpheus in some traditions"], siblings: ["artemis"], notes: ["阿斯克勒庇俄斯的母亲通常是凡女 Coronis。"] }),
    artemis: lineage({ parents: ["zeus", "leto"], siblings: ["apollo"] }),
    ares: lineage({ parents: ["zeus", "hera"], consorts: ["aphrodite"], children: ["deimos", "phobos", "harmonia", "anteros"], childNames: ["Eros in later traditions"], siblings: ["hebe", "eileithyia", "hephaestus"] }),
    aphrodite: lineage({ parents: ["dione"], parentNames: ["Sea-foam from Uranus in Hesiod"], consorts: ["hephaestus", "ares", "dionysus"], children: ["eros", "deimos", "phobos", "harmonia", "anteros", "priapus"], notes: ["阿佛洛狄忒有两条著名谱系：Hesiod 说她从乌拉诺斯的海沫生出；Homer 传统说她是宙斯与狄俄涅之女。"] }),
    hephaestus: lineage({ parents: ["hera"], parentNames: ["Zeus in some traditions"], consorts: ["aphrodite", "aglaea"], notes: ["赫淮斯托斯的出生存在异说；站内在关系图中保留赫拉独生与宙斯父系两种提示。"] }),
    hermes: lineage({ parents: ["zeus", "maia"], children: ["pan"], childNames: ["Hermaphroditus", "Autolycus"] }),
    dionysus: lineage({ parents: ["zeus"], parentNames: ["Semele"], consorts: ["aphrodite"], children: ["priapus"], notes: ["狄俄尼索斯由凡女 Semele 所生，后从宙斯大腿中完成出生。"] }),
    hades: lineage({ parents: ["cronus", "rhea"], consorts: ["persephone"], siblings: olympianSiblings.filter((id) => id !== "hades") }),
    hestia: lineage({ parents: ["cronus", "rhea"], siblings: olympianSiblings.filter((id) => id !== "hestia"), notes: ["赫斯提亚守贞，因此没有核心配偶或子女谱系。"] }),
    persephone: lineage({ parents: ["zeus", "demeter"], consorts: ["hades"], siblings: ["athena", "apollo", "artemis", "ares", "hermes", "dionysus"] }),
    eros: lineage({ parents: ["aphrodite", "ares"], siblings: ["anteros", "deimos", "phobos", "harmonia"], notes: ["早期神谱也可把 Eros 视为原初力量；丘比特式谱系常把他列为阿佛洛狄忒之子。"] }),
    nike: lineage({ parentNames: ["Pallas", "Styx"], siblings: styxSiblings.filter((id) => id !== "nike"), notes: ["Styx 带着子女最早支持宙斯，因此这些拟人神常在宙斯权力旁出现。"] }),
    hebe: lineage({ parents: ["zeus", "hera"], consortNames: ["Heracles"], siblings: ["ares", "eileithyia", "hephaestus"] }),
    iris: lineage({ parentNames: ["Thaumas", "Electra"], siblingNames: ["The Harpies"], notes: ["Iris 属于海与天空交界的信使谱系，站内没有收录她的父母。"] }),
    helios: lineage({ parents: ["hyperion", "theia"], siblings: heliadSiblings.filter((id) => id !== "helios") }),
    selene: lineage({ parents: ["hyperion", "theia"], siblings: heliadSiblings.filter((id) => id !== "selene") }),
    eos: lineage({ parents: ["hyperion", "theia"], consorts: ["astraeus"], children: windSiblings, siblings: heliadSiblings.filter((id) => id !== "eos") }),
    hecate: lineage({ parentNames: ["Perses", "Asteria"], notes: ["Hecate 的父母通常列为泰坦后裔 Perses 与 Asteria，她与勒托同属 Coeus-Phoebe 血脉的外支。"] }),
    pan: lineage({ parents: ["hermes"], parentNames: ["Dryope or Penelope"], notes: ["Pan 的母系在古代文本中有多种说法。"] }),
    asclepius: lineage({ parents: ["apollo"], parentNames: ["Coronis"], children: ["hygieia"], childNames: ["Machaon", "Podalirius", "Panacea"] }),
    hygieia: lineage({ parents: ["asclepius"], parentNames: ["Epione"], siblingNames: ["Panacea", "Iaso", "Aceso"], notes: ["医神家族中，Hygieia 代表健康与预防，Panacea 代表万灵药式疗愈。"] }),
    hypnos: lineage({ parents: ["nyx"], siblings: ["thanatos", "nemesis", "eris", "clotho", "lachesis", "atropos"], children: ["morpheus"], notes: ["Hesiod 常把 Hypnos 与 Thanatos 列为 Nyx 的孩子。"] }),
    thanatos: lineage({ parents: ["nyx"], siblings: ["hypnos", "nemesis", "eris", "clotho", "lachesis", "atropos"] }),
    morpheus: lineage({ parents: ["hypnos"], parentNames: ["Pasithea in later tradition"], siblingNames: ["Phobetor", "Phantasos"] }),
    nemesis: lineage({ parents: ["nyx"], siblings: ["hypnos", "thanatos", "eris", "clotho", "lachesis", "atropos"] }),
    tyche: lineage({ parents: ["oceanus", "tethys"], siblingNames: ["Oceanids and river gods"], notes: ["Tyche 常被列入 Oceanid 谱系，也有别的地方传统。"] }),
    themis: lineage({ parents: ["gaia", "uranus"], consorts: ["zeus"], children: ["clotho", "lachesis", "atropos"], childNames: ["The Horae"], siblings: titanSiblings.filter((id) => id !== "themis"), notes: ["命运三女神在 Hesiod 中可为 Nyx 之女；另一主流版本列为 Zeus 与 Themis 的女儿。"] }),
    leto: lineage({ parents: ["coeus", "phoebe"], consorts: ["zeus"], children: ["apollo", "artemis"], siblingNames: ["Asteria"] }),
    rhea: lineage({ parents: ["gaia", "uranus"], consorts: ["cronus"], children: olympianSiblings, siblings: titanSiblings.filter((id) => id !== "rhea") }),
    cronus: lineage({ parents: ["gaia", "uranus"], consorts: ["rhea"], children: olympianSiblings, siblings: titanSiblings.filter((id) => id !== "cronus") }),
    oceanus: lineage({ parents: ["gaia", "uranus"], consorts: ["tethys"], children: ["metis", "dione", "tyche", "peitho"], childNames: ["Rivers", "Oceanids"], siblings: titanSiblings.filter((id) => id !== "oceanus") }),
    tethys: lineage({ parents: ["gaia", "uranus"], consorts: ["oceanus"], children: ["metis", "dione", "tyche", "peitho"], childNames: ["Rivers", "Oceanids"], siblings: titanSiblings.filter((id) => id !== "tethys") }),
    hyperion: lineage({ parents: ["gaia", "uranus"], consorts: ["theia"], children: heliadSiblings, siblings: titanSiblings.filter((id) => id !== "hyperion") }),
    theia: lineage({ parents: ["gaia", "uranus"], consorts: ["hyperion"], children: heliadSiblings, siblings: titanSiblings.filter((id) => id !== "theia") }),
    coeus: lineage({ parents: ["gaia", "uranus"], consorts: ["phoebe"], children: ["leto"], childNames: ["Asteria"], siblings: titanSiblings.filter((id) => id !== "coeus") }),
    phoebe: lineage({ parents: ["gaia", "uranus"], consorts: ["coeus"], children: ["leto"], childNames: ["Asteria"], siblings: titanSiblings.filter((id) => id !== "phoebe") }),
    iapetus: lineage({ parents: ["gaia", "uranus"], parentNames: [], children: ["prometheus", "epimetheus", "atlas"], childNames: ["Menoetius"], siblings: titanSiblings.filter((id) => id !== "iapetus"), notes: ["Iapetus 的配偶常列为 Oceanid Clymene 或 Asia。"] }),
    crius: lineage({ parents: ["gaia", "uranus"], children: ["astraeus"], childNames: ["Pallas", "Perses"], siblings: titanSiblings.filter((id) => id !== "crius"), notes: ["Pallas 是 Nike、Kratos、Bia、Zelus 的父亲，Perses 则连到 Hecate 的谱系。"] }),
    mnemosyne: lineage({ parents: ["gaia", "uranus"], consorts: ["zeus"], children: museSiblings, siblings: titanSiblings.filter((id) => id !== "mnemosyne") }),
    prometheus: lineage({ parents: ["iapetus"], parentNames: ["Clymene or Asia"], siblings: ["epimetheus", "atlas"], notes: ["Prometheus 属于 Iapetus 家族，常与人类起源和文明火种绑定。"] }),
    epimetheus: lineage({ parents: ["iapetus"], parentNames: ["Clymene or Asia"], consortNames: ["Pandora"], siblings: ["prometheus", "atlas"] }),
    atlas: lineage({ parents: ["iapetus"], parentNames: ["Clymene or Asia"], children: ["maia"], childNames: ["The Pleiades", "The Hesperides in some traditions"], siblings: ["prometheus", "epimetheus"] }),
    metis: lineage({ parents: ["oceanus", "tethys"], consorts: ["zeus"], children: ["athena"], siblingNames: ["Oceanids"], notes: ["Metis 是宙斯吞下的智慧女神，也是雅典娜母系的关键。"] }),
    dione: lineage({ parents: ["oceanus", "tethys"], consorts: ["zeus"], children: ["aphrodite"], notes: ["Homeric tradition makes Dione mother of Aphrodite; Hesiodic tradition gives Aphrodite a sea-foam birth."] }),
    astraeus: lineage({ parents: ["crius"], parentNames: ["Eurybia"], consorts: ["eos"], children: windSiblings, childNames: ["The stars"] }),
    amphitrite: lineage({ parents: ["nereus"], parentNames: ["Doris"], consorts: ["poseidon"], children: ["triton"], siblings: nereidSiblings.filter((id) => id !== "amphitrite") }),
    triton: lineage({ parents: ["poseidon", "amphitrite"] }),
    proteus: lineage({ parentNames: ["Genealogy varies"], notes: ["Proteus 的核心身份是会变形的海老人；谱系在古代材料中不如 Nereus 一支稳定。"] }),
    nereus: lineage({ parents: ["pontus", "gaia"], consortNames: ["Doris"], children: nereidSiblings, childNames: ["The Nereids"] }),
    thetis: lineage({ parents: ["nereus"], parentNames: ["Doris"], consortNames: ["Peleus"], childNames: ["Achilles"], siblings: nereidSiblings.filter((id) => id !== "thetis") }),
    galatea: lineage({ parents: ["nereus"], parentNames: ["Doris"], siblings: nereidSiblings.filter((id) => id !== "galatea") }),
    boreas: lineage({ parents: ["astraeus", "eos"], siblings: windSiblings.filter((id) => id !== "boreas"), childNames: ["Zetes", "Calais", "Chione"] }),
    zephyrus: lineage({ parents: ["astraeus", "eos"], siblings: windSiblings.filter((id) => id !== "zephyrus") }),
    notus: lineage({ parents: ["astraeus", "eos"], siblings: windSiblings.filter((id) => id !== "notus") }),
    eurus: lineage({ parents: ["astraeus", "eos"], siblings: windSiblings.filter((id) => id !== "eurus") }),
    aeolus: lineage({ parentNames: ["Hippotes"], notes: ["《奥德赛》中的 Aeolus 更像受神眷顾的风之看守者，不是四大风神的直系父亲。"] }),
    glaucus: lineage({ parentNames: ["Mortal fisherman before apotheosis"], notes: ["Glaucus 的重点是由凡人变为海神，因此谱系不如海神家族稳定。"] }),
    leucothea: lineage({ parentNames: ["Ino, daughter of Cadmus"], notes: ["Leucothea 原为凡女 Ino，死后成为救助航海者的海中女神。"] }),
    gaia: lineage({ parentNames: ["Appears after Chaos in Hesiod"], consorts: ["uranus", "pontus"], children: ["uranus", "pontus", ...titanSiblings], childNames: ["Cyclopes", "Hecatoncheires", "Giants"], notes: ["在 Hesiod 中，Gaia 不是通常意义上的 Chaos 之女，而是在 Chaos 之后出现；她也能独自生出 Uranus、Mountains 和 Pontus。"] }),
    uranus: lineage({ parents: ["gaia"], consorts: ["gaia"], children: titanSiblings, childNames: ["Cyclopes", "Hecatoncheires"] }),
    nyx: lineage({ parents: ["chaos"], consorts: ["erebus"], children: ["aether", "hemera", "hypnos", "thanatos", "nemesis", "eris", "clotho", "lachesis", "atropos"], childNames: ["Many spirits of fate and hardship"] }),
    erebus: lineage({ parents: ["chaos"], consorts: ["nyx"], children: ["aether", "hemera"] }),
    tartarus: lineage({ parentNames: ["Appears among the earliest primordial beings"], consortNames: ["Gaia in the Typhon story"], childNames: ["Typhon"], notes: ["Tartarus 在 Hesiod 中既是深渊也是原初存在，严格父母关系不完全等同后代神。"] }),
    aether: lineage({ parents: ["nyx", "erebus"], siblings: ["hemera"] }),
    hemera: lineage({ parents: ["nyx", "erebus"], siblings: ["aether"] }),
    pontus: lineage({ parents: ["gaia"], consorts: ["gaia"], children: ["nereus"], childNames: ["Thaumas", "Phorcys", "Ceto", "Eurybia"] }),
    chaos: lineage({ children: ["nyx", "erebus"], childNames: ["Gaia and Tartarus appear next in the cosmogony"], notes: ["Chaos 更接近最初的裂隙；Nyx 与 Erebus 明确由 Chaos 生出，Gaia 与 Tartarus 则是在创世序列中随后出现。"] }),
    phanes: lineage({ notes: ["Phanes 属于 Orphic 神谱，不在 Hesiod 主线家族树中；站内单列以提示希腊神话存在多套创世谱系。"] }),
    clotho: lineage({ parents: ["nyx"], parentNames: ["Zeus and Themis in another major tradition"], siblings: fateSiblings.filter((id) => id !== "clotho") }),
    lachesis: lineage({ parents: ["nyx"], parentNames: ["Zeus and Themis in another major tradition"], siblings: fateSiblings.filter((id) => id !== "lachesis") }),
    atropos: lineage({ parents: ["nyx"], parentNames: ["Zeus and Themis in another major tradition"], siblings: fateSiblings.filter((id) => id !== "atropos") }),
    eris: lineage({ parents: ["nyx"], childNames: ["Ponos", "Lethe", "Limos", "Algea", "Horkos"], siblings: ["hypnos", "thanatos", "nemesis", "clotho", "lachesis", "atropos"] }),
    harmonia: lineage({ parents: ["ares", "aphrodite"], consortNames: ["Cadmus"], siblings: ["deimos", "phobos", "anteros"] }),
    enyo: lineage({ parentNames: ["Genealogy varies"], siblings: ["ares"], notes: ["Enyo 更常作为 Ares 的战场同伴出现；有的传统把她列入 Zeus 与 Hera 的战争谱系。"] }),
    deimos: lineage({ parents: ["ares", "aphrodite"], siblings: ["phobos", "harmonia", "anteros"] }),
    phobos: lineage({ parents: ["ares", "aphrodite"], siblings: ["deimos", "harmonia", "anteros"] }),
    eileithyia: lineage({ parents: ["zeus", "hera"], siblings: ["ares", "hebe", "hephaestus"] }),
    peitho: lineage({ parents: ["oceanus", "tethys"], notes: ["Peitho 常与 Aphrodite 同行；她的谱系有 Oceanid 和 Aphrodite 伴随神两种理解方式。"] }),
    hymen: lineage({ parentNames: ["Apollo and a Muse in some traditions"], notes: ["Hymen 的父母说法分散；作为婚礼之神，他在仪式功能上比谱系更稳定。"] }),
    priapus: lineage({ parents: ["dionysus", "aphrodite"], notes: ["Priapus 的父亲有 Dionysus、Hermes、Pan 等异说；Dionysus 与 Aphrodite 是常见组合。"] }),
    anteros: lineage({ parents: ["ares", "aphrodite"], siblings: ["eros", "deimos", "phobos", "harmonia"] }),
    kratos: lineage({ parentNames: ["Pallas", "Styx"], siblings: styxSiblings.filter((id) => id !== "kratos") }),
    bia: lineage({ parentNames: ["Pallas", "Styx"], siblings: styxSiblings.filter((id) => id !== "bia") }),
    zelus: lineage({ parentNames: ["Pallas", "Styx"], siblings: styxSiblings.filter((id) => id !== "zelus") }),
    aglaea: lineage({ parents: ["zeus"], parentNames: ["Eurynome"], consorts: ["hephaestus"], siblingNames: ["Euphrosyne", "Thalia the Grace"], notes: ["这里的 Thalia 是三美惠之一，不是站内第 98 位喜剧缪斯 Thalia。"] }),
    calliope: lineage({ parents: ["zeus", "mnemosyne"], childNames: ["Orpheus", "Linus in some traditions"], siblings: museSiblings.filter((id) => id !== "calliope") }),
    clio: lineage({ parents: ["zeus", "mnemosyne"], siblings: museSiblings.filter((id) => id !== "clio") }),
    erato: lineage({ parents: ["zeus", "mnemosyne"], siblings: museSiblings.filter((id) => id !== "erato") }),
    euterpe: lineage({ parents: ["zeus", "mnemosyne"], siblings: museSiblings.filter((id) => id !== "euterpe") }),
    melpomene: lineage({ parents: ["zeus", "mnemosyne"], childNames: ["Sirens in some traditions"], siblings: museSiblings.filter((id) => id !== "melpomene") }),
    polyhymnia: lineage({ parents: ["zeus", "mnemosyne"], siblings: museSiblings.filter((id) => id !== "polyhymnia") }),
    terpsichore: lineage({ parents: ["zeus", "mnemosyne"], childNames: ["Sirens in some traditions"], siblings: museSiblings.filter((id) => id !== "terpsichore") }),
    "thalia-muse": lineage({ parents: ["zeus", "mnemosyne"], siblings: museSiblings.filter((id) => id !== "thalia-muse") }),
    urania: lineage({ parents: ["zeus", "mnemosyne"], siblings: museSiblings.filter((id) => id !== "urania") }),
    maia: lineage({ parents: ["atlas"], parentNames: ["Pleione"], consorts: ["zeus"], children: ["hermes"], siblingNames: ["The other Pleiades"] })
  };

  window.mythLineageSources = [
    { label: "Theoi Greek Gods Family Tree", url: "https://www.theoi.com/Tree.html" },
    { label: "Hesiod, Theogony, Perseus", url: "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0130%3Acard%3D104" }
  ];
})();
